version: '3.3'
services:
  api:
    image: registry.gitlab.com/everest-mobile-seiii-se/safebox/safebox-api
    configs:
      - source: api
        target: /app/config.toml
    networks:
      - public
      - private
    deploy:
      labels:
        - "traefik.frontend.rule=Host:safebox.jerson.dev"
        - "traefik.port=8000"
        - "traefik.docker.network=public"

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=safebox
      - MYSQL_PASSWORD=safebox
      - MYSQL_DATABASE=safebox
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    networks:
      - private

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    networks:
      - public
      - private
    deploy:
      labels:
        - "traefik.frontend.rule=Host:mysql-safebox.jerson.dev"
        - "traefik.port=80"
        - "traefik.docker.network=public"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

networks:
  public:
    external: true
  private:


volumes:
  mysql:

configs:
  api:
    external:
      name: safebox_api_prod