version: '3.7'
services:
  api:
    image: registry.gitlab.com/everest-mobile-seiii-se/safebox/safebox-api
    configs:
      - source: api
        target: /app/config.toml
    networks:
      - public
      - private
    secrets:
      - google_play
    ports:
      - 50051:50051
    dns:
      - 8.8.8.8
    deploy:
      replicas: 3
      labels:
        - "traefik.frontend.rule=Host:safebox.jerson.dev"
        - "traefik.port=8000"
        - "traefik.docker.network=public"

  cron:
    image: registry.gitlab.com/everest-mobile-seiii-se/safebox/safebox-api/cron
    configs:
      - source: api
        target: /app/config.toml
    networks:
      - private

  queue:
    image: registry.gitlab.com/everest-mobile-seiii-se/safebox/safebox-api/queue
    configs:
      - source: api
        target: /app/config.toml
    deploy:
      replicas: 2
    networks:
      - private

  commands:
    image: registry.gitlab.com/everest-mobile-seiii-se/safebox/safebox-api/commands
    stdin_open: true
    tty: true
    entrypoint: sh
    configs:
      - source: api
        target: /app/config.toml
    networks:
      - private

  mysql:
    image: mysql:8.0
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=safebox
      - MYSQL_PASSWORD=safebox
      - MYSQL_DATABASE=safebox
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
    networks:
      - private

  rabbitmq:
    image: rabbitmq:3.6-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - private

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    networks:
      - public
      - private
    deploy:
      labels:
        - "traefik.frontend.rule=Host:mysql-safebox.jerson.dev"
        - "traefik.port=80"
        - "traefik.docker.network=public"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

networks:
  public:
    external: true
  private:


volumes:
  rabbitmq:
  mysql:

secrets:
  google_play:
    external:
      name: safebox_google_play

configs:
  api:
    external:
      name: safebox_api_prod