version: '3.7'
services:
  server:
    image: jerson/go:1.12
    ports:
      - 8000:8000
      - 50051:50051
    working_dir: /srv/go/src/safebox.jerson.dev/api
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    volumes:
      - ./:/srv/go/src/safebox.jerson.dev/api
    entrypoint: sh

  mysql:
    image: mysql:8.0
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  rabbitmq:
    image: rabbitmq:3.6-alpine

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8090:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
