[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.2"

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "1.6.0"

[[constraint]]
  name = "github.com/improbable-eng/grpc-web"
  version = "0.9.6"

[[constraint]]
  name = "github.com/jinzhu/configor"
  version = "1.1.1"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.10"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.22.0"

[prune]
  go-tests = true
  unused-packages = true
