CREATE DATABASE /*!32312 IF NOT EXISTS */ `safebox` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

CREATE USER IF NOT EXISTS 'safebox'@'localhost'
  IDENTIFIED BY 'safebox';
GRANT ALL PRIVILEGES ON *.* TO 'safebox'@'localhost'
WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'safebox'@'%'
  IDENTIFIED BY 'safebox';
GRANT ALL PRIVILEGES ON *.* TO 'safebox'@'%'
WITH GRANT OPTION;